name: "Firebase"
description: "Sets up firebase tools"
inputs:
  serviceAccount:
    description: "Service account json file to use for authentication"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Cache firebase binary
      id: firebase-cache
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/firebase
          ~/.cache/firebase/tools
        key: ${{ runner.os }}-firebase-tools-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-firebase-tools-
    - name: Install firebase-tools
      run: curl -sL firebase.tools | analytics=false bash
      shell: bash
    - name: Check tools embedded npm
      continue-on-error: true
      id: checkIsNpm
      run: |
        firebase is:npm > /dev/null 2> /dev/null
      shell: bash
    - name: Update firebase-tools with version check
      if: steps.checkIsNpm.outcome == 'sucess'
      run: |
        if [ `firebase is:npm view firebase-tools version` != `firebase --version` ]; then
          curl -sL firebase.tools | analytics=false upgrade=true bash
        fi
      shell: bash
    - name: Force update firebase-tools
      if: steps.checkIsNpm.outcome == 'failure'
      run: |
        curl -sL firebase.tools | analytics=false upgrade=true bash
        if [ `firebase --version` == "12.4.4" ]; then
          echo !!! Downgrading broken 12.4.4 version to 12.4.3
          UNAME=$(uname -s | tr '[:upper:]' '[:lower:]')
          case "$UNAME" in
               linux*)     MACHINE=linux;;
               darwin*)    MACHINE=macos;;
          esac
          INSTALL_DIR="/usr/local/bin"
          DOWNLOAD_URL="https://firebase.tools/bin/$MACHINE/v12.4.3"
          echo "-- Downloading binary from $DOWNLOAD_URL"
          sudo curl -o "$INSTALL_DIR/firebase" -L --progress-bar $DOWNLOAD_URL
          sudo chmod +rx "$INSTALL_DIR/firebase"
        fi
      shell: bash
    - name: Set service account
      if: "${{ inputs.serviceAccount != '' }}"
      run: |
        echo '${{ inputs.serviceAccount }}' > $RUNNER_TEMP/.firebase_service_account.json
        echo GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/.firebase_service_account.json >> $GITHUB_ENV
      shell: bash
