name: 'Firebase'
description: 'Sets up firebase tools'
inputs:
  serviceAccount:
    description: 'Service account json file to use for authentication'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Cache firebase binary
      id: firebase-cache
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/firebase
          ~/.cache/firebase/tools
        key: ${{ runner.os }}-firebase-tools-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-firebase-tools-
    - name: Install firebase-tools
      run: curl -sL firebase.tools | analytics=false bash
      shell: bash
    - name: Update firebase-tools
      run: |
        if [ `firebase is:npm view firebase-tools version --userconfig=$RUNNER_TEMP/dummynpmrc` != `firebase --version` ]; then
          curl -sL firebase.tools | analytics=false upgrade=true bash
        fi
      shell: bash
    - name: Set service account
      if: "${{ inputs.serviceAccount != '' }}"
      run: |
        echo '${{ inputs.serviceAccount }}' > $RUNNER_TEMP/.firebase_service_account.json
        echo GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/.firebase_service_account.json >> $GITHUB_ENV
      shell: bash
